version: '3.7'

services:
  meetup-elasticsearch:
    container_name: meetup-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    ports:
      - "9201:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml